# Generated by Django 4.2.11 on 2024-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_type_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='firstFlight',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='post',
            name='manufacturer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='numberBuilt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
